In [1]:
df = pd.read_csv('iris.csv')

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [37]:
df = pd.read_csv('iris.csv')

In [4]:
print(df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
val = df[df['variety'] == 'Iris-setosa']

In [6]:
print(val)

Empty DataFrame
Columns: [sepal.length, sepal.width, petal.length, petal.width, variety]
Index: []

In [41]:
val = df[df['variety'] == 'iris-Setosa']

In [42]:
print(val)

Empty DataFrame
Columns: [sepal.length, sepal.width, petal.length, petal.width, variety]
Index: []

In [12]:
val = df[df['variety'] == 'Setosa' and df['sepal.width]>3.5]

SyntaxError: EOL while scanning string literal (1613113530.py, line 1)

In [14]:
val = df[(df['variety'] == 'Setosa') & (df['sepal.width'] > 3.5)]

In [15]:
print(val)

    sepal.length  sepal.width  petal.length  petal.width variety
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
10           5.4          3.7           1.5          0.2  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
21           5.1          3.7           1.5          0.4  Setosa
22           4.6          3.6           1.0          0.2  Setosa
32           5.2          4.1           1.5          0.1  Setosa
33           5.5          4.2           1.4          0.2  Setosa
37           4.9          3.6           1.4          0.1  Setosa
44           5.1          3.8           1.9          0.4  Setosa
46           5.1          3.8           1.6          0.2  Setosa
48           5.3          3.7           1.5          0.2  Setosa

In [19]:
val = df.rename(columns={'sepal.width': 'Sepal_Width'})

In [20]:
val

     sepal.length  Sepal_Width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [27]:
df['SepalArea'] = df['sepal.length'] * df['Sepal_Width']

In [22]:
column_names = df.columns.tolist()

In [23]:
print(column_names)

['sepal.length', 'Sepal_Width', 'petal.length', 'petal.width', 'variety', 'SepalArea']

In [26]:
val

0      17.85
1      14.70
2      15.04
3      14.26
4      18.00
       ...
145    20.10
146    15.75
147    19.50
148    21.08
149    17.70
Length: 150, dtype: float64

In [28]:
df

,sepal.length,Sepal_Width,petal.length,petal.width,variety,SepalArea
0,5.1,3.5,1.4,0.2,Setosa,17.85
1,4.9,3.0,1.4,0.2,Setosa,14.70
2,4.7,3.2,1.3,0.2,Setosa,15.04
3,4.6,3.1,1.5,0.2,Setosa,14.26
4,5.0,3.6,1.4,0.2,Setosa,18.00
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica,20.10
146,6.3,2.5,5.0,1.9,Virginica,15.75
147,6.5,3.0,5.2,2.0,Virginica,19.50
148,6.2,3.4,5.4,2.3,Virginica,21.08
149,5.9,3.0,5.1,1.8,Virginica,17.70

In [29]:
value = df.drop_duplicates(subset=['sepal.length', 'Sepal_Width', 'variety'], inplace=True)

In [30]:
value

In [31]:
print(value)

None

In [32]:
df

,sepal.length,Sepal_Width,petal.length,petal.width,variety,SepalArea
0,5.1,3.5,1.4,0.2,Setosa,17.85
1,4.9,3.0,1.4,0.2,Setosa,14.70
2,4.7,3.2,1.3,0.2,Setosa,15.04
3,4.6,3.1,1.5,0.2,Setosa,14.26
4,5.0,3.6,1.4,0.2,Setosa,18.00
...,...,...,...,...,...,...
143,6.8,3.2,5.9,2.3,Virginica,21.76
145,6.7,3.0,5.2,2.3,Virginica,20.10
146,6.3,2.5,5.0,1.9,Virginica,15.75
148,6.2,3.4,5.4,2.3,Virginica,21.08
149,5.9,3.0,5.1,1.8,Virginica,17.70

In [33]:
value = df.drop_duplicates(subset=[ 'variety'], inplace=True)

In [34]:
print(value)

None

In [35]:
df

,sepal.length,Sepal_Width,petal.length,petal.width,variety,SepalArea
0,5.1,3.5,1.4,0.2,Setosa,17.85
50,7.0,3.2,4.7,1.4,Versicolor,22.40
100,6.3,3.3,6.0,2.5,Virginica,20.79

In [38]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [45]:
values = df[df['variety'] == 'Setosa']

In [46]:
print(values)

    sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa
21           5.1          3.7           1.5          0.4  Setosa
22           4.6          3.6           1.0          0.2  Setosa
23           5.1          3.3           1.7          0.5  Setosa
24           4.8          3.4           1.9          0.2  Setosa
25           5.0          3.0           1.6          0.2  Setosa
26           5.0          3.4           1.6          0.4  Setosa
27           5.2          3.5           1.5          0.2  Setosa
28           5.2          3.4           1.4          0.2  Setosa
29           4.7          3.2           1.6          0.2  Setosa
30           4.8          3.1           1.6          0.2  Setosa
31           5.4          3.4           1.5          0.4  Setosa
32           5.2          4.1           1.5          0.1  Setosa
33           5.5          4.2           1.4          0.2  Setosa
34           4.9          3.1           1.5          0.2  Setosa
35           5.0          3.2           1.2          0.2  Setosa
36           5.5          3.5           1.3          0.2  Setosa
37           4.9          3.6           1.4          0.1  Setosa
38           4.4          3.0           1.3          0.2  Setosa
39           5.1          3.4           1.5          0.2  Setosa
40           5.0          3.5           1.3          0.3  Setosa
41           4.5          2.3           1.3          0.3  Setosa
42           4.4          3.2           1.3          0.2  Setosa
43           5.0          3.5           1.6          0.6  Setosa
44           5.1          3.8           1.9          0.4  Setosa
45           4.8          3.0           1.4          0.3  Setosa
46           5.1          3.8           1.6          0.2  Setosa
47           4.6          3.2           1.4          0.2  Setosa
48           5.3          3.7           1.5          0.2  Setosa
49           5.0          3.3           1.4          0.2  Setosa

In [47]:
df['variety'] = df['variety'].replace('Setosa', 'Iris-setosa')

In [48]:
df

     sepal.length  sepal.width  petal.length  petal.width      variety
0             5.1          3.5           1.4          0.2  Iris-setosa
1             4.9          3.0           1.4          0.2  Iris-setosa
2             4.7          3.2           1.3          0.2  Iris-setosa
3             4.6          3.1           1.5          0.2  Iris-setosa
4             5.0          3.6           1.4          0.2  Iris-setosa
..            ...          ...           ...          ...          ...
145           6.7          3.0           5.2          2.3    Virginica
146           6.3          2.5           5.0          1.9    Virginica
147           6.5          3.0           5.2          2.0    Virginica
148           6.2          3.4           5.4          2.3    Virginica
149           5.9          3.0           5.1          1.8    Virginica

[150 rows x 5 columns]

In [49]:
values = df[df['variety'] == 'Iris-setosa']

In [50]:
print(values)

    sepal.length  sepal.width  petal.length  petal.width      variety
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
15           5.7          4.4           1.5          0.4  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa
17           5.1          3.5           1.4          0.3  Iris-setosa
18           5.7          3.8           1.7          0.3  Iris-setosa
19           5.1          3.8           1.5          0.3  Iris-setosa
20           5.4          3.4           1.7          0.2  Iris-setosa
21           5.1          3.7           1.5          0.4  Iris-setosa
22           4.6          3.6           1.0          0.2  Iris-setosa
23           5.1          3.3           1.7          0.5  Iris-setosa
24           4.8          3.4           1.9          0.2  Iris-setosa
25           5.0          3.0           1.6          0.2  Iris-setosa
26           5.0          3.4           1.6          0.4  Iris-setosa
27           5.2          3.5           1.5          0.2  Iris-setosa
28           5.2          3.4           1.4          0.2  Iris-setosa
29           4.7          3.2           1.6          0.2  Iris-setosa
30           4.8          3.1           1.6          0.2  Iris-setosa
31           5.4          3.4           1.5          0.4  Iris-setosa
32           5.2          4.1           1.5          0.1  Iris-setosa
33           5.5          4.2           1.4          0.2  Iris-setosa
34           4.9          3.1           1.5          0.2  Iris-setosa
35           5.0          3.2           1.2          0.2  Iris-setosa
36           5.5          3.5           1.3          0.2  Iris-setosa
37           4.9          3.6           1.4          0.1  Iris-setosa
38           4.4          3.0           1.3          0.2  Iris-setosa
39           5.1          3.4           1.5          0.2  Iris-setosa
40           5.0          3.5           1.3          0.3  Iris-setosa
41           4.5          2.3           1.3          0.3  Iris-setosa
42           4.4          3.2           1.3          0.2  Iris-setosa
43           5.0          3.5           1.6          0.6  Iris-setosa
44           5.1          3.8           1.9          0.4  Iris-setosa
45           4.8          3.0           1.4          0.3  Iris-setosa
46           5.1          3.8           1.6          0.2  Iris-setosa
47           4.6          3.2           1.4          0.2  Iris-setosa
48           5.3          3.7           1.5          0.2  Iris-setosa
49           5.0          3.3           1.4          0.2  Iris-setosa

In [51]:
df.to_csv('cleaned_iris.csv',index=False)

In [52]:
df

     sepal.length  sepal.width  petal.length  petal.width      variety
0             5.1          3.5           1.4          0.2  Iris-setosa
1             4.9          3.0           1.4          0.2  Iris-setosa
2             4.7          3.2           1.3          0.2  Iris-setosa
3             4.6          3.1           1.5          0.2  Iris-setosa
4             5.0          3.6           1.4          0.2  Iris-setosa
..            ...          ...           ...          ...          ...
145           6.7          3.0           5.2          2.3    Virginica
146           6.3          2.5           5.0          1.9    Virginica
147           6.5          3.0           5.2          2.0    Virginica
148           6.2          3.4           5.4          2.3    Virginica
149           5.9          3.0           5.1          1.8    Virginica

[150 rows x 5 columns]

In [53]:
sort = df.sort_values(by='sepal.width', ascending=True)

In [54]:
print(sort)

     sepal.length  sepal.width  petal.length  petal.width      variety
60            5.0          2.0           3.5          1.0   Versicolor
62            6.0          2.2           4.0          1.0   Versicolor
119           6.0          2.2           5.0          1.5    Virginica
68            6.2          2.2           4.5          1.5   Versicolor
41            4.5          2.3           1.3          0.3  Iris-setosa
..            ...          ...           ...          ...          ...
16            5.4          3.9           1.3          0.4  Iris-setosa
14            5.8          4.0           1.2          0.2  Iris-setosa
32            5.2          4.1           1.5          0.1  Iris-setosa
33            5.5          4.2           1.4          0.2  Iris-setosa
15            5.7          4.4           1.5          0.4  Iris-setosa

[150 rows x 5 columns]

In [55]:
sort = df.sort_values(by='sepal.width', ascending=False)

In [56]:
print(sort)

     sepal.length  sepal.width  petal.length  petal.width      variety
15            5.7          4.4           1.5          0.4  Iris-setosa
33            5.5          4.2           1.4          0.2  Iris-setosa
32            5.2          4.1           1.5          0.1  Iris-setosa
14            5.8          4.0           1.2          0.2  Iris-setosa
16            5.4          3.9           1.3          0.4  Iris-setosa
..            ...          ...           ...          ...          ...
87            6.3          2.3           4.4          1.3   Versicolor
62            6.0          2.2           4.0          1.0   Versicolor
68            6.2          2.2           4.5          1.5   Versicolor
119           6.0          2.2           5.0          1.5    Virginica
60            5.0          2.0           3.5          1.0   Versicolor

[150 rows x 5 columns]

In [57]:
duplicate = df.duplicated()

In [58]:
print(duplicate)

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [59]:
unique = df.drop_duplicates()

In [60]:
print(unique)

     sepal.length  sepal.width  petal.length  petal.width      variety
0             5.1          3.5           1.4          0.2  Iris-setosa
1             4.9          3.0           1.4          0.2  Iris-setosa
2             4.7          3.2           1.3          0.2  Iris-setosa
3             4.6          3.1           1.5          0.2  Iris-setosa
4             5.0          3.6           1.4          0.2  Iris-setosa
..            ...          ...           ...          ...          ...
145           6.7          3.0           5.2          2.3    Virginica
146           6.3          2.5           5.0          1.9    Virginica
147           6.5          3.0           5.2          2.0    Virginica
148           6.2          3.4           5.4          2.3    Virginica
149           5.9          3.0           5.1          1.8    Virginica

[149 rows x 5 columns]

In [63]:
from openpyxl import load_workbook

In [62]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 24.3.1 is available.
You should consider upgrading via the 'C:\Users\tarunkumar.s\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [64]:
wb = load_workbook('cleaned_iris.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'cleaned_iris.xlsx'